### ISSUE TITLE
tcmalloc.cc - attempt to free invalid pointer

### ISSUE THREAD

**Issue by x0unmaze** [nguu/stable-diffusion#1]
When the launch.py command is executed by the notebook, the program pauses and reports an error:
`src/tcmalloc.cc:283] Attempt to free invalid pointer 0x597db5167740`

I removed the command `%env LD_PRELOAD=libtcmalloc.so`, and application is work again, but Colab doesn't free up RAM.

**Comment by x0unmaze** [comment]
Commit https://github.com/nguu/stable-diffusion/commit/f0ebecf930504f8524d7ea2c2b0003415f42a526 only reduces the RAM increase when switching checkpoints.

When the app first ran, the RAM was up to 9GB.
I can switch between checkpoints and only stay at about 9GB of RAM, but when I use the ControlNet models, the RAM keeps going up.

**Comment by nguu** [comment]
> Commit [f0ebecf](https://github.com/nguu/stable-diffusion/commit/f0ebecf930504f8524d7ea2c2b0003415f42a526) only reduces the RAM increase when switching checkpoints.
> 
> When the app first ran, the RAM was up to 9GB. I can switch between checkpoints and only stay at about 9GB of RAM, but when I use the ControlNet models, the RAM keeps going up.

After testing, more RAM will be used by the A1111 repository `v1.4.*` tags.
When running app, you can choose the `v1.3.0` or `v1.5.0-RC` tags, which lower RAM from 9GB to ~6.5GB.

I'll provide an update so that you can choose tags directly in Colab.

**Comment by x0unmaze** [comment]
It's working!
The RAM used to be 11~12GB when the software was running with 2–3 controlnet models, but it is currently just 9.5GB.
